services:
  mysql8:
    image: services:mysql8
    container_name: services_mysql8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - siri_network
  redis:
    image: redis:2.8
    container_name: services_redis
    ports:
      - "6379:6379"
    networks:
      - siri_network
networks:
  default:
    name: $DOCKER_NETWORK
    external: true
