services:
  lb:
    image: traefik:v2.3
    container_name: balancer
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "1936:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - neo_network

networks:
  neo_network:
    external: true
